apiVersion: v1
kind: Service
metadata:
  name: aidocsearch-app
  namespace: aidocsearch
  labels:
    app: aidocsearch
    component: app
spec:
  type: NodePort
  selector:
    app: aidocsearch
    component: app
  ports:
  - name: http
    port: 8501
    targetPort: 8501
    nodePort: 30850
    protocol: TCP
